let arr = [1,2,[3,[4,5,6,[7,8]]]];

let arr1 = arr.flat(2);//Intha number based on the nested array in the single array.......
let arr2 = arr.flat(Infinity);  // Itha use panni yathana nested array irrunthalum atha single array akum....
console.log(arr1);
console.log(arr2);