let arr = [10,20,30,40,20,10,50];
let arr1 = arr.indexOf(20,2);// Ithu index printing 1st iruku rathu value 2nd irruku rathu nth no of time in array...
console.log(arr1);
let arr2 = arr.lastIndexOf(20,2);// ithu index printing from the reverse la irrunthu indexing pannum same like before thaan...
console.log(arr2);