//array declaration
let arr = [1,2,3,4,5];
//arr.every use panni function condition loop full ahh execute ana mattum thaan true one false analum false...
let arr1 = arr.every( (element,index,value)=> {//------->   .every => na every loop is true naa thaan true varum
    return element%2==0;//condition in the return element....
})
//calling every function in the console...
console.log(arr1);
//arr.some use panni function condition loop full ahh execute ana mattum thaan true ahh onu irruntha lum true thaan....
let arr2 = arr.some( (element,index,value)=> {//-------->   .some => na any one loop is true naa lee true varum
    return element%2==0;
})
//calling some function in the console...
console.log(arr2);